// <auto-generated />
using System;
using BIATeam.BIAMonitoring.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BIATeam.BIAMonitoring.Infrastructure.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BIA.Net.Core.Domain.DistCache.Entities.DistCache", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(449)
                        .HasColumnType("nvarchar(449)");

                    b.Property<DateTimeOffset?>("AbsoluteExpiration")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAtTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("SlidingExpirationInSeconds")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Value")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtTime")
                        .HasDatabaseName("Index_ExpiresAtTime");

                    b.ToTable("DistCache");
                });

            modelBuilder.Entity("BIA.Net.Core.Domain.Translation.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "EN",
                            Name = "English"
                        },
                        new
                        {
                            Id = 2,
                            Code = "FR",
                            Name = "Français"
                        },
                        new
                        {
                            Id = 3,
                            Code = "ES",
                            Name = "Española"
                        },
                        new
                        {
                            Id = 4,
                            Code = "DE",
                            Name = "Deutsch"
                        });
                });

            modelBuilder.Entity("BIATeam.BIAMonitoring.Domain.Audit.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuditAction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuditChanges")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AuditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuditUserLogin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Table")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("BIATeam.BIAMonitoring.Domain.Notification.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("JData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Read")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("TypeId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("BIATeam.BIAMonitoring.Domain.Notification.Entities.NotificationTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NotificationId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId");

                    b.HasIndex("TeamId");

                    b.ToTable("NotificationTeam");
                });

            modelBuilder.Entity("BIATeam.BIAMonitoring.Domain.Notification.Entities.NotificationTeamRole", b =>
                {
                    b.Property<int>("NotificationTeamId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("NotificationTeamId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("NotificationTeamRole");
                });

            modelBuilder.Entity("BIATeam.BIAMonitoring.Domain.Notification.Entities.NotificationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("NotificationTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "task",
                            Label = "Task"
                        },
                        new
                        {
                            Id = 2,
                            Code = "info",
                            Label = "Info"
                        },
                        new
                        {
                            Id = 3,
                            Code = "success",
                            Label = "Success"
                        },
                        new
                        {
                            Id = 4,
                            Code = "warn",
                            Label = "Warn"
                        },
                        new
                        {
                            Id = 5,
                            Code = "error",
                            Label = "Error"
                        });
                });

            modelBuilder.Entity("BIATeam.BIAMonitoring.Domain.Notification.Entities.NotificationUser", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("NotificationId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("UserId", "NotificationId");

                    b.HasIndex("NotificationId");

                    b.ToTable("NotificationUser");
                });

            modelBuilder.Entity("BIATeam.BIAMonitoring.Domain.Translation.Entities.NotificationTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("NotificationId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("NotificationId", "LanguageId")
                        .IsUnique();

                    b.ToTable("NotificationTranslations");
                });

            modelBuilder.Entity("BIATeam.BIAMonitoring.Domain.Translation.Entities.NotificationTypeTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("NotificationTypeId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("NotificationTypeId", "LanguageId")
                        .IsUnique();

                    b.ToTable("NotificationTypeTranslations");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Label = "Tâche",
                            LanguageId = 2,
                            NotificationTypeId = 1
                        },
                        new
                        {
                            Id = 102,
                            Label = "Tarea",
                            LanguageId = 3,
                            NotificationTypeId = 1
                        },
                        new
                        {
                            Id = 103,
                            Label = "Aufgabe",
                            LanguageId = 4,
                            NotificationTypeId = 1
                        },
                        new
                        {
                            Id = 201,
                            Label = "Information",
                            LanguageId = 2,
                            NotificationTypeId = 2
                        },
                        new
                        {
                            Id = 202,
                            Label = "Información",
                            LanguageId = 3,
                            NotificationTypeId = 2
                        },
                        new
                        {
                            Id = 203,
                            Label = "Information",
                            LanguageId = 4,
                            NotificationTypeId = 2
                        },
                        new
                        {
                            Id = 301,
                            Label = "Succès",
                            LanguageId = 2,
                            NotificationTypeId = 3
                        },
                        new
                        {
                            Id = 302,
                            Label = "Éxito",
                            LanguageId = 3,
                            NotificationTypeId = 3
                        },
                        new
                        {
                            Id = 303,
                            Label = "Erfolg",
                            LanguageId = 4,
                            NotificationTypeId = 3
                        },
                        new
                        {
                            Id = 401,
                            Label = "Avertissement",
                            LanguageId = 2,
                            NotificationTypeId = 4
                        },
                        new
                        {
                            Id = 402,
                            Label = "Advertencia",
                            LanguageId = 3,
                            NotificationTypeId = 4
                        },
                        new
                        {
                            Id = 403,
                            Label = "Erwärmen",
                            LanguageId = 4,
                            NotificationTypeId = 4
                        },
                        new
                        {
                            Id = 501,
                            Label = "Erreur",
                            LanguageId = 2,
                            NotificationTypeId = 5
                        },
                        new
                        {
                            Id = 502,
                            Label = "Culpa",
                            LanguageId = 3,
                            NotificationTypeId = 5
                        },
                        new
                        {
                            Id = 503,
                            Label = "Fehler",
                            LanguageId = 4,
                            NotificationTypeId = 5
                        });
                });

            modelBuilder.Entity("BIATeam.BIAMonitoring.Domain.Translation.Entities.RoleTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("RoleId", "LanguageId")
                        .IsUnique();

                    b.ToTable("RoleTranslations");

                    b.HasData(
                        new
                        {
                            Id = 1000101,
                            Label = "Administrateur",
                            LanguageId = 2,
                            RoleId = 10001
                        },
                        new
                        {
                            Id = 1000102,
                            Label = "Administrador",
                            LanguageId = 3,
                            RoleId = 10001
                        },
                        new
                        {
                            Id = 1000103,
                            Label = "Administrator",
                            LanguageId = 4,
                            RoleId = 10001
                        },
                        new
                        {
                            Id = 1000201,
                            Label = "Administrateur des tâches en arrière-plan",
                            LanguageId = 2,
                            RoleId = 10002
                        },
                        new
                        {
                            Id = 1000202,
                            Label = "Administrador de tareas en segundo plano",
                            LanguageId = 3,
                            RoleId = 10002
                        },
                        new
                        {
                            Id = 1000203,
                            Label = "Administrator für Hintergrundaufgaben",
                            LanguageId = 4,
                            RoleId = 10002
                        },
                        new
                        {
                            Id = 1000301,
                            Label = "Visualisation des tâches en arrière-plan",
                            LanguageId = 2,
                            RoleId = 10003
                        },
                        new
                        {
                            Id = 1000302,
                            Label = "Visualización de tareas en segundo plano",
                            LanguageId = 3,
                            RoleId = 10003
                        },
                        new
                        {
                            Id = 1000303,
                            Label = "Visualisierung von Hintergrundaufgaben",
                            LanguageId = 4,
                            RoleId = 10003
                        },
                        new
                        {
                            Id = 101,
                            Label = "Administrateur du site",
                            LanguageId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 102,
                            Label = "Administrador del sitio",
                            LanguageId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 103,
                            Label = "Seitenadministrator",
                            LanguageId = 4,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("BIATeam.BIAMonitoring.Domain.User.Entities.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TeamId", "UserId")
                        .IsUnique();

                    b.ToTable("Members");
                });

            modelBuilder.Entity("BIATeam.BIAMonitoring.Domain.User.Entities.MemberRole", b =>
                {
                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("MemberId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("MemberRole");
                });

            modelBuilder.Entity("BIATeam.BIAMonitoring.Domain.User.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 10001,
                            Code = "Admin",
                            Label = "Administrator"
                        },
                        new
                        {
                            Id = 10002,
                            Code = "Back_Admin",
                            Label = "Background task administrator"
                        },
                        new
                        {
                            Id = 10003,
                            Code = "Back_Read_Only",
                            Label = "Visualization of background tasks"
                        },
                        new
                        {
                            Id = 1,
                            Code = "Site_Admin",
                            Label = "Site administrator"
                        });
                });

            modelBuilder.Entity("BIATeam.BIAMonitoring.Domain.User.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("TeamTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("TeamTypeId");

                    b.ToTable("Teams", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("BIATeam.BIAMonitoring.Domain.User.Entities.TeamType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("TeamTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Root"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Site"
                        });
                });

            modelBuilder.Entity("BIATeam.BIAMonitoring.Domain.User.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("DaiDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DistinguishedName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ExternalCompany")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmployee")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExternal")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Manager")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Office")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Site")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SubDepartment")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BIATeam.BIAMonitoring.Domain.User.Entities.UserAudit", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditId"));

                    b.Property<string>("AuditAction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuditChanges")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AuditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuditUserLogin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("--");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("AuditId");

                    b.ToTable("UsersAudit");
                });

            modelBuilder.Entity("BIATeam.BIAMonitoring.Domain.View.Entities.View", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Preference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TableId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ViewType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Views");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Name = "default",
                            Preference = "{\"first\":0,\"rows\":10,\"sortField\":\"createdDate\",\"sortOrder\":-1,\"columnOrder\":[\"titleTranslated\",\"descriptionTranslated\",\"type\",\"read\",\"createdDate\",\"createdBy\"],\"selection\":[],\"filters\":{}}",
                            TableId = "notificationsGrid",
                            ViewType = 0
                        });
                });

            modelBuilder.Entity("BIATeam.BIAMonitoring.Domain.View.Entities.ViewTeam", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("ViewId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("TeamId", "ViewId");

                    b.HasIndex("ViewId");

                    b.ToTable("ViewTeam");
                });

            modelBuilder.Entity("BIATeam.BIAMonitoring.Domain.View.Entities.ViewUser", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ViewId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("UserId", "ViewId");

                    b.HasIndex("ViewId");

                    b.ToTable("ViewUser");
                });

            modelBuilder.Entity("RoleTeamType", b =>
                {
                    b.Property<int>("RolesId")
                        .HasColumnType("int");

                    b.Property<int>("TeamTypesId")
                        .HasColumnType("int");

                    b.HasKey("RolesId", "TeamTypesId");

                    b.HasIndex("TeamTypesId");

                    b.ToTable("RoleTeamTypes", (string)null);

                    b.HasData(
                        new
                        {
                            RolesId = 10001,
                            TeamTypesId = 1
                        },
                        new
                        {
                            RolesId = 10002,
                            TeamTypesId = 1
                        },
                        new
                        {
                            RolesId = 10003,
                            TeamTypesId = 1
                        },
                        new
                        {
                            RolesId = 1,
                            TeamTypesId = 2
                        });
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<int>("RolesId")
                        .HasColumnType("int");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("RolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("BIATeam.BIAMonitoring.Domain.Site.Entities.Site", b =>
                {
                    b.HasBaseType("BIATeam.BIAMonitoring.Domain.User.Entities.Team");

                    b.Property<byte[]>("RowVersionSite")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("RowVersion");

                    b.ToTable("Sites", (string)null);
                });

            modelBuilder.Entity("BIATeam.BIAMonitoring.Domain.Notification.Entities.Notification", b =>
                {
                    b.HasOne("BIATeam.BIAMonitoring.Domain.User.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("BIATeam.BIAMonitoring.Domain.Notification.Entities.NotificationType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("BIATeam.BIAMonitoring.Domain.Notification.Entities.NotificationTeam", b =>
                {
                    b.HasOne("BIATeam.BIAMonitoring.Domain.Notification.Entities.Notification", "Notification")
                        .WithMany("NotifiedTeams")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BIATeam.BIAMonitoring.Domain.User.Entities.Team", "Team")
                        .WithMany("NotificationTeams")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Notification");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("BIATeam.BIAMonitoring.Domain.Notification.Entities.NotificationTeamRole", b =>
                {
                    b.HasOne("BIATeam.BIAMonitoring.Domain.Notification.Entities.NotificationTeam", "NotificationTeam")
                        .WithMany("Roles")
                        .HasForeignKey("NotificationTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BIATeam.BIAMonitoring.Domain.User.Entities.Role", "Role")
                        .WithMany("NotificationTeamRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotificationTeam");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BIATeam.BIAMonitoring.Domain.Notification.Entities.NotificationUser", b =>
                {
                    b.HasOne("BIATeam.BIAMonitoring.Domain.Notification.Entities.Notification", "Notification")
                        .WithMany("NotifiedUsers")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BIATeam.BIAMonitoring.Domain.User.Entities.User", "User")
                        .WithMany("NotificationUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Notification");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BIATeam.BIAMonitoring.Domain.Translation.Entities.NotificationTranslation", b =>
                {
                    b.HasOne("BIA.Net.Core.Domain.Translation.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BIATeam.BIAMonitoring.Domain.Notification.Entities.Notification", "Notification")
                        .WithMany("NotificationTranslations")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("BIATeam.BIAMonitoring.Domain.Translation.Entities.NotificationTypeTranslation", b =>
                {
                    b.HasOne("BIA.Net.Core.Domain.Translation.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BIATeam.BIAMonitoring.Domain.Notification.Entities.NotificationType", "NotificationType")
                        .WithMany("NotificationTypeTranslations")
                        .HasForeignKey("NotificationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("NotificationType");
                });

            modelBuilder.Entity("BIATeam.BIAMonitoring.Domain.Translation.Entities.RoleTranslation", b =>
                {
                    b.HasOne("BIA.Net.Core.Domain.Translation.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BIATeam.BIAMonitoring.Domain.User.Entities.Role", "Role")
                        .WithMany("RoleTranslations")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BIATeam.BIAMonitoring.Domain.User.Entities.Member", b =>
                {
                    b.HasOne("BIATeam.BIAMonitoring.Domain.User.Entities.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BIATeam.BIAMonitoring.Domain.User.Entities.User", "User")
                        .WithMany("Members")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BIATeam.BIAMonitoring.Domain.User.Entities.MemberRole", b =>
                {
                    b.HasOne("BIATeam.BIAMonitoring.Domain.User.Entities.Member", "Member")
                        .WithMany("MemberRoles")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BIATeam.BIAMonitoring.Domain.User.Entities.Role", "Role")
                        .WithMany("MemberRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BIATeam.BIAMonitoring.Domain.User.Entities.Team", b =>
                {
                    b.HasOne("BIATeam.BIAMonitoring.Domain.User.Entities.TeamType", "TeamType")
                        .WithMany()
                        .HasForeignKey("TeamTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeamType");
                });

            modelBuilder.Entity("BIATeam.BIAMonitoring.Domain.View.Entities.ViewTeam", b =>
                {
                    b.HasOne("BIATeam.BIAMonitoring.Domain.User.Entities.Team", "Team")
                        .WithMany("ViewTeams")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BIATeam.BIAMonitoring.Domain.View.Entities.View", "View")
                        .WithMany("ViewTeams")
                        .HasForeignKey("ViewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("View");
                });

            modelBuilder.Entity("BIATeam.BIAMonitoring.Domain.View.Entities.ViewUser", b =>
                {
                    b.HasOne("BIATeam.BIAMonitoring.Domain.User.Entities.User", "User")
                        .WithMany("ViewUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BIATeam.BIAMonitoring.Domain.View.Entities.View", "View")
                        .WithMany("ViewUsers")
                        .HasForeignKey("ViewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("View");
                });

            modelBuilder.Entity("RoleTeamType", b =>
                {
                    b.HasOne("BIATeam.BIAMonitoring.Domain.User.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BIATeam.BIAMonitoring.Domain.User.Entities.TeamType", null)
                        .WithMany()
                        .HasForeignKey("TeamTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("BIATeam.BIAMonitoring.Domain.User.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BIATeam.BIAMonitoring.Domain.User.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BIATeam.BIAMonitoring.Domain.Site.Entities.Site", b =>
                {
                    b.HasOne("BIATeam.BIAMonitoring.Domain.User.Entities.Team", null)
                        .WithOne()
                        .HasForeignKey("BIATeam.BIAMonitoring.Domain.Site.Entities.Site", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BIATeam.BIAMonitoring.Domain.Notification.Entities.Notification", b =>
                {
                    b.Navigation("NotificationTranslations");

                    b.Navigation("NotifiedTeams");

                    b.Navigation("NotifiedUsers");
                });

            modelBuilder.Entity("BIATeam.BIAMonitoring.Domain.Notification.Entities.NotificationTeam", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("BIATeam.BIAMonitoring.Domain.Notification.Entities.NotificationType", b =>
                {
                    b.Navigation("NotificationTypeTranslations");
                });

            modelBuilder.Entity("BIATeam.BIAMonitoring.Domain.User.Entities.Member", b =>
                {
                    b.Navigation("MemberRoles");
                });

            modelBuilder.Entity("BIATeam.BIAMonitoring.Domain.User.Entities.Role", b =>
                {
                    b.Navigation("MemberRoles");

                    b.Navigation("NotificationTeamRoles");

                    b.Navigation("RoleTranslations");
                });

            modelBuilder.Entity("BIATeam.BIAMonitoring.Domain.User.Entities.Team", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("NotificationTeams");

                    b.Navigation("ViewTeams");
                });

            modelBuilder.Entity("BIATeam.BIAMonitoring.Domain.User.Entities.User", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("NotificationUsers");

                    b.Navigation("ViewUsers");
                });

            modelBuilder.Entity("BIATeam.BIAMonitoring.Domain.View.Entities.View", b =>
                {
                    b.Navigation("ViewTeams");

                    b.Navigation("ViewUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
